export const STEEL_IMAGES = {
  hero: '/products/steel/steel_hero2.jpg',
  pipesTubes: {
    types: {
      seamless: {
        stainlessSteelSeamlessPipes1Png: '/products/steel/pipes-tubes/types/seamless/stainless-steel-seamless-pipes1.png',
        stainlessSteelRoundPipe1Png: '/products/steel/pipes-tubes/types/seamless/stainless-steel-round-pipe1.png',
        schedule40SeamlessStainlessSteelPipe1Png: '/products/steel/pipes-tubes/types/seamless/schedule-40-seamless-stainless-steel-pipe1.png',
        coldRolledSeamlessStainlessSteelPipe1Png: '/products/steel/pipes-tubes/types/seamless/cold-rolled-seamless-stainless-steel-pipe1.png',
        stainlessSteelHighPressurePipe1Png: '/products/steel/pipes-tubes/types/seamless/stainless-steel-high-pressure-pipe1.png',
      },
      erw: {
        stainlessSteelWeldedPipe1Png: '/products/steel/pipes-tubes/types/erw/stainless-steel-welded-pipe1.png',
        stainlessSteelEfwPipe1Png: '/products/steel/pipes-tubes/types/erw/stainless-steel-efw-pipe1.png',
        largeDiameterStainlessSteelWeldedPipe1Png: '/products/steel/pipes-tubes/types/erw/large-diameter-stainless-steel-welded-pipe1.png',
        stainlessSteelSpiralWeldedPipe1Png: '/products/steel/pipes-tubes/types/erw/stainless-steel-spiral-welded-pipe1.png',
        sch10SsWeldedPipe1Png: '/products/steel/pipes-tubes/types/erw/sch-10-ss-welded-pipe1.png',
      },
      tube: {
        stainlessSteelSeamlessTube11Png: '/products/steel/pipes-tubes/types/tube/stainless-steel-seamless-tube1.png',
        ssWeldedTubing11Png: '/products/steel/pipes-tubes/types/tube/ss-welded-tubing1.png',
        coldDrawnStainlessSteelTube11Png: '/products/steel/pipes-tubes/types/tube/cold-drawn-stainless-steel-tube1.png',
        stainlessSteelRoundTube11Png: '/products/steel/pipes-tubes/types/tube/stainless-steel-round-tube1.png',
        ssThickWallTubes11Png: '/products/steel/pipes-tubes/types/tube/ss-thick-wall-tubes1.png',
      },
      polished: {
        stainlessSteelPolishedPipe1Png: '/products/steel/pipes-tubes/types/polished/stainless-steel-polished-pipe1.png',
        stainlessSteelPolishedTubing1Png: '/products/steel/pipes-tubes/types/polished/stainless-steel-polished-tubing1.png',
        astmA554Gr304PolishedPipe1Png: '/products/steel/pipes-tubes/types/polished/astm-a554-gr-304-polished-pipe1.png',
        polishedStainlessSteelTube1Png: '/products/steel/pipes-tubes/types/polished/polished-stainless-steel-tube1.png',
        astmA554Gr201PolishedPipe1Png: '/products/steel/pipes-tubes/types/polished/astm-a554-gr-201-polished-pipe1.png',
      },
      heatExchanger: {
        stainlessSteelHeatExchangerTubes1Png: '/products/steel/pipes-tubes/types/heat-exchanger/stainless-steel-heat-exchanger-tubes1.png',
        stainlessSteelCoilTubingHeatExchanger1Png: '/products/steel/pipes-tubes/types/heat-exchanger/stainless-steel-coil-tubing-heat-exchanger1.png',
        stainlessSteelShellAndTubeHeatExchanger1Png: '/products/steel/pipes-tubes/types/heat-exchanger/stainless-steel-shell-and-tube-heat-exchanger1.png',
        stainlessSteelHeatExchangerStraightTubing1Png: '/products/steel/pipes-tubes/types/heat-exchanger/stainless-steel-heat-exchanger-straight-tubing1.png',
        ssSeamlessHeatExchangerTubes1Png: '/products/steel/pipes-tubes/types/heat-exchanger/ss-seamless-heat-exchanger-tubes1.png',
      },
      boiler: {
        stainlessSteelBoilerTube1Png: '/products/steel/pipes-tubes/types/boiler/stainless-steel-boiler-tube1.png',
        ss304SeamlessBoilerTubing1Png: '/products/steel/pipes-tubes/types/boiler/ss-304-seamless-boiler-tubing1.png',
        stainlessSteelWaterTubeBoiler1Png: '/products/steel/pipes-tubes/types/boiler/stainless-steel-water-tube-boiler1.png',
        ssSeamlessBoilerTubes1Png: '/products/steel/pipes-tubes/types/boiler/ss-seamless-boiler-tubes1.png',
        stainlessSteelWeldedBoilerTube1Png: '/products/steel/pipes-tubes/types/boiler/stainless-steel-welded-boiler-tube1.png',
      },
      duplex: {
        duplex2205SeamlessPipe1Png: '/products/steel/pipes-tubes/types/duplex/duplex-2205-seamless-pipe1.png',
        duplex2205Tube1Png: '/products/steel/pipes-tubes/types/duplex/duplex-2205-tube1.png',
        astmA790GrS32205Tubing1Png: '/products/steel/pipes-tubes/types/duplex/astm-a790-gr-s32205-tubing1.png',
        duplexStainlessSteelPipe1Png: '/products/steel/pipes-tubes/types/duplex/duplex-stainless-steel-pipe1.png',
        '2205SteelErwPipe1Pngg': '/products/steel/pipes-tubes/types/duplex/2205-steel-erw-pipe1.png',
      },
      hollow: {
        stainlessSteelSquareHollowSection1Png: '/products/steel/pipes-tubes/types/hollow/stainless-steel-square-hollow-section1.png',
        stainlessSteelCircularHollowSection1Png: '/products/steel/pipes-tubes/types/hollow/stainless-steel-circular-hollow-section1.png',
        astmA554Grade201RectangularHollowTube1Png: '/products/steel/pipes-tubes/types/hollow/astm-a554-grade-201-rectangular-hollow-tube1.png',
        ss316CircularHollowTube1Png: '/products/steel/pipes-tubes/types/hollow/ss-316-circular-hollow-tube1.png',
        astmA554Tp316lSeamlessHollowTube1Png: '/products/steel/pipes-tubes/types/hollow/astm-a554-tp-316l-seamless-hollow-tube1.png',
      },
      conduit: {
        stainlessSteelConduitTube1Png: '/products/steel/pipes-tubes/types/conduit/stainless-steel-conduit-tube1.png',
        stainlessSteelConduits1Png: '/products/steel/pipes-tubes/types/conduit/stainless-steel-conduits1.png',
        electricalMetallicTubing1Png: '/products/steel/pipes-tubes/types/conduit/electrical-metallic-tubing1.png',
        aisi316lRigidStainlessSteelConduit1Png: '/products/steel/pipes-tubes/types/conduit/aisi-316l-rigid-stainless-steel-conduit1.png',
        stainlessSteelFlexibleConduit1Png: '/products/steel/pipes-tubes/types/conduit/stainless-steel-flexible-conduit1.png',
      },
      gi: {
        galvanisedIronPipe: '/products/steel/pipes-tubes/types/gi_pipe/Galvanised-Iron-Pipe.png',
        threadedUtilityPipe: '/products/steel/pipes-tubes/types/gi_pipe/Customised-Steel-Pipe.png',
        pipesTubes: '/products/steel/pipes-tubes/types/gi_pipe/GI_Conduit_Runs.png',
        pipesTubes1: '/products/steel/pipes-tubes/types/gi_pipe/Commercial_Utility_Pipe.png',
        structuralSteel: '/products/steel/pipes-tubes/types/gi_pipe/Plant_Support_Conduit.png',
      },
      ms: {
        customisedSteelPipe: '/products/steel/pipes-tubes/types/ms_pipe/Customised-Steel-Pipe.png',
        projectLinePipe: '/products/steel/pipes-tubes/types/ms_pipe/project_line_pipe.png',
        mildSteelPipeStock: '/products/steel/pipes-tubes/types/ms_pipe/mild_steel_pipe_stock.png',
        fabricationPipeSupply: '/products/steel/pipes-tubes/types/ms_pipe/fabrication_pipe_supply.png',
        industrialSupportPipe: '/products/steel/pipes-tubes/types/ms_pipe/industrial_support_pipe.png',
      },
    },
    erwPipe1: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_ERW_pipe.png',
    industrialTube1: '/products/steel/pipes-tubes/pipe_tubes/industrial_tube.png',
    polishedTube1: '/products/steel/pipes-tubes/pipe_tubes/polished_tube.png',
    heatExchangerTube1: '/products/steel/pipes-tubes/pipe_tubes/heat-exchanger-tube.png',
    boilerTube1: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_boiler_tubes.png',
    conduitPipe: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_conduit_pipe.png',
    seamlessPipe: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_seamless_pipe.png',
    duplexPipe1: '/products/steel/pipes-tubes/pipe_tubes/duplex_pipe.png',
    hollowSection1: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_hollow_section.png',
    conduitPipe1: '/products/steel/pipes-tubes/pipe_tubes/stainless_steel_conduit_pipe.png',
    giPipe: '/products/steel/pipes-tubes/pipe_tubes/Galvanized_Iron_Conduit_Pipe.png',
    carbonPipe: '/products/steel/pipes-tubes/pipe_tubes/carbon_steel.png',
  },
  sheetsPlates: {
    sheetsPlates: '/products/steel/SHEETS&PLATES.png',
    ssSheets: '/products/steel/sheets-plates/shared/ss-sheets.png',
    ssPlates: '/products/steel/sheets-plates/shared/ss-plates.png',
    steelCoils: '/products/steel/sheets-plates/titanium_coil.png',
    ssStrips: '/products/steel/sheets-plates/shared/ss-strips.png',
    ssCircle: '/products/steel/sheets-plates/shared/ss-circle.png',
    types: {
      ssPerforatedSheet: '/products/steel/sheets-plates/shared/ss-perforated-sheet.png',
      csPerforatedSheet: '/products/steel/sheets-plates/shared/cs-perforated-sheet.png',
    },
    ssChequeredPlate: '/products/steel/sheets-plates/shared/ss-chequered-plate.png',
    ssFlats: '/products/steel/sheets-plates/shared/ss-flats.png',
    csCoils: '/products/steel/sheets-plates/carbon_steel_coil.png',
    csSheets: '/products/steel/sheets-plates/shared/cs-sheets.png',
    csPlates: '/products/steel/sheets-plates/shared/cs-plates.png',
    carbonCoils: '/products/steel/sheets-plates/shared/carbon-coils.png',
    csStips: '/products/steel/sheets-plates/shared/cs-stips.png',
    csFoils: '/products/steel/sheets-plates/shared/cs-foils.png',
    csChequeredPlate: '/products/steel/sheets-plates/shared/cs-chequered-plate.png',
    csCircles: '/products/steel/sheets-plates/shared/cs-circles.png',
    ssCoils: '/products/steel/sheets-plates/alloy_Nickel_coils.png',
    ssFoils: '/products/steel/sheets-plates/shared/ss-foils.png',
    ssPerforatedSheet: '/products/steel/sheets-plates/shared/ss-perforated-sheet.png',
  },
  pipeFittings: {
    types: {
      buttWeld: {
        pipeFittingElbowCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-elbow-card.jpg',
        pipeFittingTeeCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-tee-card.jpg',
        pipeFittingReducersCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-reducers-card.jpg',
        pipeFittingPipeBendCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-pipe-bend-card.jpg',
        pipeFittingStubEndCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-stub-end-card.jpg',
        pipeFittingCapCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-cap-card.jpg',
        pipeFittingCrossCard: '/products/steel/pipe-fittings/types/butt-weld/pipe-fitting-cross-card.jpg',
      },
      forged: {
        forgedFittingElbowCard: '/products/steel/pipe-fittings/types/forged/forged-fitting-elbow-card.jpg',
        forgedFittingCrossTee: '/products/steel/pipe-fittings/types/forged/forged-fitting-cross-tee.jpg',
        forgedFittingsCap: '/products/steel/pipe-fittings/types/forged/forged-fittings-cap.jpg',
        forgedFittingsUnion: '/products/steel/pipe-fittings/types/forged/forged-fittings-union.jpg',
        forgedFittingsPlugBushing: '/products/steel/pipe-fittings/types/forged/forged-fittings-plug-bushing.jpg',
        forgedFittingsSwageNipple: '/products/steel/pipe-fittings/types/forged/forged-fittings-swage-nipple.jpg',
      },
    },
  },
  flanges: {
    slipOnFlange: '/products/steel/flanges/slip-on-flange.jpg',
    blindSpectacleBlindBanner: '/products/steel/flanges/blind-spectacle-blind-banner.jpg',
    lapJointFlangeBanner: '/products/steel/flanges/lap-joint-flange-banner.jpg',
    socketWeldFlangeBanner: '/products/steel/flanges/socket-weld-flange-banner.jpg',
    weldNeckFlange: '/products/steel/flanges/weld-neck-flange.jpg',
    orificeFlangeBanner: '/products/steel/flanges/orifice-flange-banner.jpg',
    threadedFlangeBanner: '/products/steel/flanges/threaded-flange-banner.jpg',
  },
  fasteners: {
    stainless: '/products/steel/fasteners-bars/stainless.jpg',
    types: {
      stainlessFasteners: {
        s1: '/products/steel/fasteners-bars/types/stainless-fasteners/s1.png',
        s2: '/products/steel/fasteners-bars/types/stainless-fasteners/s2.png',
        s3: '/products/steel/fasteners-bars/types/stainless-fasteners/s3.png',
        s4: '/products/steel/fasteners-bars/types/stainless-fasteners/s4.png',
        s6: '/products/steel/fasteners-bars/types/stainless-fasteners/s6.png',
        s7: '/products/steel/fasteners-bars/types/stainless-fasteners/s7.png',
        s8: '/products/steel/fasteners-bars/types/stainless-fasteners/s8.png',
        s9: '/products/steel/fasteners-bars/types/stainless-fasteners/s9.png',
        s10: '/products/steel/fasteners-bars/types/stainless-fasteners/s10.png',
        s11: '/products/steel/fasteners-bars/types/stainless-fasteners/s11.png',
        s12: '/products/steel/fasteners-bars/types/stainless-fasteners/s12.png',
        s13: '/products/steel/fasteners-bars/types/stainless-fasteners/s13.png',
      },
      hexBolts: {
        hex1: '/products/steel/fasteners-bars/types/hex-bolts/hex1.png',
        hex2: '/products/steel/fasteners-bars/types/hex-bolts/hex2.png',
        hex3: '/products/steel/fasteners-bars/types/hex-bolts/hex3.png',
        hex4: '/products/steel/fasteners-bars/types/hex-bolts/hex4.png',
      },
      hexNuts: {
        n1: '/products/steel/fasteners-bars/types/hex-nuts/n1.png',
        n2: '/products/steel/fasteners-bars/types/hex-nuts/n2.png',
        n4: '/products/steel/fasteners-bars/types/hex-nuts/n4.png',
        in1: '/products/steel/fasteners-bars/types/hex-nuts/in1.png',
        in3: '/products/steel/fasteners-bars/types/hex-nuts/in3.png',
        in4: '/products/steel/fasteners-bars/types/hex-nuts/in4.png',
        in5: '/products/steel/fasteners-bars/types/hex-nuts/in5.png',
      },
      washers: {
        w1: '/products/steel/fasteners-bars/types/washers/w1.png',
        w2: '/products/steel/fasteners-bars/types/washers/w2.png',
        w3: '/products/steel/fasteners-bars/types/washers/w3.png',
        w4: '/products/steel/fasteners-bars/types/washers/w4.png',
      },
      petrochemicalStudBolts: {
        s1: '/products/steel/fasteners-bars/types/petrochemical-stud-bolts/s1.png',
        s2: '/products/steel/fasteners-bars/types/petrochemical-stud-bolts/s2.png',
      },
      structuralAssemblies: {
        a1: '/products/steel/fasteners-bars/types/structural-assemblies/a1.png',
        a2: '/products/steel/fasteners-bars/types/structural-assemblies/a2.png',
        a3: '/products/steel/fasteners-bars/types/structural-assemblies/a3.png',
        a4: '/products/steel/fasteners-bars/types/structural-assemblies/a4.png',
        a5: '/products/steel/fasteners-bars/types/structural-assemblies/a5.png',
        a6: '/products/steel/fasteners-bars/types/structural-assemblies/a6.png',
        a7: '/products/steel/fasteners-bars/types/structural-assemblies/a7.png',
        a9: '/products/steel/fasteners-bars/types/structural-assemblies/a9.png',
        a10: '/products/steel/fasteners-bars/types/structural-assemblies/a10.png',
        a11: '/products/steel/fasteners-bars/types/structural-assemblies/a11.png',
        a12: '/products/steel/fasteners-bars/types/structural-assemblies/a12.png',
        a13: '/products/steel/fasteners-bars/types/structural-assemblies/a13.png',
        a15: '/products/steel/fasteners-bars/types/structural-assemblies/a15.png',
        a16: '/products/steel/fasteners-bars/types/structural-assemblies/a16.png',
        a17: '/products/steel/fasteners-bars/types/structural-assemblies/a17.png',
        a18: '/products/steel/fasteners-bars/types/structural-assemblies/a18.png',
        a19: '/products/steel/fasteners-bars/types/structural-assemblies/a18.png',
        a20: '/products/steel/fasteners-bars/types/structural-assemblies/a20.png',
        a21: '/products/steel/fasteners-bars/types/structural-assemblies/a21.png',
        a22: '/products/steel/fasteners-bars/types/structural-assemblies/a22.png',
        a23: '/products/steel/fasteners-bars/types/structural-assemblies/a23.png',
        a24: '/products/steel/fasteners-bars/types/structural-assemblies/a24.png',
      },
      specialFastenersBars: {
        s1: '/products/steel/fasteners-bars/types/special-fasteners-bars/s1.png',
        s2: '/products/steel/fasteners-bars/types/special-fasteners-bars/s2.png',
        s3: '/products/steel/fasteners-bars/types/special-fasteners-bars/s3.png',
        s4: '/products/steel/fasteners-bars/types/special-fasteners-bars/s4.png',
        s5: '/products/steel/fasteners-bars/types/special-fasteners-bars/s5.png',
        s6: '/products/steel/fasteners-bars/types/special-fasteners-bars/s6.png',
        s7: '/products/steel/fasteners-bars/types/special-fasteners-bars/s7.png',
        s8: '/products/steel/fasteners-bars/types/special-fasteners-bars/s8.png',
        s9: '/products/steel/fasteners-bars/types/special-fasteners-bars/s9.png',
        s10: '/products/steel/fasteners-bars/types/special-fasteners-bars/s10.png',
        s11: '/products/steel/fasteners-bars/types/special-fasteners-bars/s11.png',
        s12: '/products/steel/fasteners-bars/types/special-fasteners-bars/s12.png',
        s13: '/products/steel/fasteners-bars/types/special-fasteners-bars/s13.png',
        s14: '/products/steel/fasteners-bars/types/special-fasteners-bars/s14.png',
        s15: '/products/steel/fasteners-bars/types/special-fasteners-bars/s15.png',
        s16: '/products/steel/fasteners-bars/types/special-fasteners-bars/s16.png',
        s17: '/products/steel/fasteners-bars/types/special-fasteners-bars/s17.png',
        s18: '/products/steel/fasteners-bars/types/special-fasteners-bars/s18.png',
        s19: '/products/steel/fasteners-bars/types/special-fasteners-bars/s19.png',
      },
    },
    hexbolts: '/products/steel/fasteners-bars/hexbolts.jpg',
    hexnut: '/products/steel/fasteners-bars/hexnut.jpg',
    washers: '/products/steel/fasteners-bars/washers.jpg',
    studbolt: '/products/steel/fasteners-bars/studbolt.jpg',
    structurebolt: '/products/steel/fasteners-bars/structurebolt.jpg',
    special: '/products/steel/fasteners-bars/special.jpg',
  },
  sealingGaskets: {
    types: {
      ringGasket: {
        ringGasketOctagonal: '/products/steel/sealing-gaskets/types/ring-gasket/ring-gasket---octagonal.jpg',
        ringGasketOval: '/products/steel/sealing-gaskets/types/ring-gasket/ring-gasket---oval.jpg',
        bxTypeRingGaskets: '/products/steel/sealing-gaskets/types/ring-gasket/bx-type-ring-gaskets.png',
        sbxTypeRingGaskets: '/products/steel/sealing-gaskets/types/ring-gasket/sbx-type-ring-gaskets.jpg',
        rxTypesRingGaskets: '/products/steel/sealing-gaskets/types/ring-gasket/rx-types-ring-gaskets.png',
        zincCoatedRingGasket: '/products/steel/sealing-gaskets/types/ring-gasket/zinc-coated-ring-gasket.jpg',
        seatRings: '/products/steel/sealing-gaskets/types/ring-gasket/seat-rings.jpg',
        silverCoatedGasket: '/products/steel/sealing-gaskets/types/ring-gasket/silver-coated-gasket.jpg',
        lipSeal: '/products/steel/sealing-gaskets/types/ring-gasket/lip-seal.jpg',
        bonnetGasket: '/products/steel/sealing-gaskets/types/ring-gasket/bonnet-gasket.jpg',
        ringGasketWithPtfeInserted: '/products/steel/sealing-gaskets/types/ring-gasket/ring-gasket-with-ptfe-inserted.png',
        bridgemanGaskets: '/products/steel/sealing-gaskets/types/ring-gasket/bridgeman-gaskets.png',
        rTypeKammprofileGasketsAdapter: '/products/steel/sealing-gaskets/types/ring-gasket/r-type-kammprofile-gaskets---adapter.png',
        ringTypeBlindGaskets: '/products/steel/sealing-gaskets/types/ring-gasket/ring-type-blind-gaskets.png',
        rTypeKammprofileGasketsOctagonal: '/products/steel/sealing-gaskets/types/ring-gasket/r-type-kammprofile-gaskets---octagonal.png',
      },
      spiralWoundGasket: {
        typeCgi: '/products/steel/sealing-gaskets/types/spiral-wound-gasket/type-cgi.jpg',
        typeCg: '/products/steel/sealing-gaskets/types/spiral-wound-gasket/type-cg.jpg',
        typeGi: '/products/steel/sealing-gaskets/types/spiral-wound-gasket/type-gi.jpg',
        typeG: '/products/steel/sealing-gaskets/types/spiral-wound-gasket/type-g.jpg',
      },
      ixGaskets: {
        ixRingAssembledInCompactFlangePosition: '/products/steel/sealing-gaskets/types/ix-gaskets/ix-ring-assembled-in-compact-flange-position.jpg',
        ixRingBlue: '/products/steel/sealing-gaskets/types/ix-gaskets/ix-ring-blue.jpg',
        ixRingOrange: '/products/steel/sealing-gaskets/types/ix-gaskets/ix-ring-orange.jpg',
        ixRingYellow: '/products/steel/sealing-gaskets/types/ix-gaskets/ix-ring-yellow.jpg',
      },
      insulationGasket: {
        typeD: '/products/steel/sealing-gaskets/types/insulation-gasket/type-d.jpg',
        typeDG10: '/products/steel/sealing-gaskets/types/insulation-gasket/type-d-g10.jpg',
        typeE: '/products/steel/sealing-gaskets/types/insulation-gasket/type-e.jpg',
        typeF: '/products/steel/sealing-gaskets/types/insulation-gasket/type-f.jpg',
        typeFG10316: '/products/steel/sealing-gaskets/types/insulation-gasket/type-f-g10-316.jpg',
        typeFG10Ptf: '/products/steel/sealing-gaskets/types/insulation-gasket/type-f-g10-ptf.jpg',
      },
      rubberGasket: {
        fullFaceType: '/products/steel/sealing-gaskets/types/rubber-gasket/full-face-type.jpg',
        raisedFace: '/products/steel/sealing-gaskets/types/rubber-gasket/raised-face.jpg',
        customizedRubberGasket: '/products/steel/sealing-gaskets/types/rubber-gasket/customized-rubber-gasket.jpg',
      },
      metalGasket: {
        spiralWoundGasket: '/products/steel/sealing-gaskets/spiral-wound-gasket.png',
        metalJacketedGaskets: '/products/steel/sealing-gaskets/types/metal-gasket/metal-jacketed-gaskets.jpg',
        ringGaskets: '/products/steel/sealing-gaskets/types/metal-gasket/ring-gaskets.jpg',
      },
      hammerUnion: {
        fig50Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-50-union.jpg',
        fig100Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-100-union.jpg',
        fig200Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-200-union.jpg',
        fig206Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-206-union.jpg',
        fig211Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-211-union.jpg',
        fig400Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-400-union.jpg',
        fig600Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-600-union.jpg',
        fig602Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-602-union.jpg',
        fig1002Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-1002-union.jpg',
        fig1003Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-1003-union.jpg',
        fig1502Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-1502-union.jpg',
        fig20022202Union: '/products/steel/sealing-gaskets/types/hammer-union/fig-2002-2202-union.jpg',
      },
      ptfeAndCnafGaskets: {
        reinforcedgraphiteGasketReinforcements: '/products/steel/sealing-gaskets/types/ptfe-and-cnaf-gaskets/reinforcedgraphite-gasket-reinforcements.jpg',
        generalCompressedNonAsbestosFibre: '/products/steel/sealing-gaskets/types/ptfe-and-cnaf-gaskets/general-compressed-non-asbestos-fibre.jpg',
      },
      metalJacketedGasket: {
        singleJacketedGasket: '/products/steel/sealing-gaskets/types/metal-jacketed-gasket/single-jacketed-gasket.jpg',
        corrugatedGasket: '/products/steel/sealing-gaskets/types/metal-jacketed-gasket/corrugated-gasket.jpg',
        solidGasket: '/products/steel/sealing-gaskets/types/metal-jacketed-gasket/solid-gasket.jpg',
        metalJacktedGasket: '/products/steel/sealing-gaskets/types/metal-jacketed-gasket/metal-jackted-gasket.jpg',
      },
    },
  },
};
