export const STEEL_IMAGES = {
  hero: '/Steel/steel_hero2.jpg',
  pipesTubes: {
    seamlessPipe1: '/Steel/pipes-tubes/seamless-pipe1.png',
    types: {
      seamless: {
        stainlessSteelSeamlessPipes1Png: '/Steel/pipes-tubes/types/seamless/stainless-steel-seamless-pipes1.png',
        stainlessSteelRoundPipe1Png: '/Steel/pipes-tubes/types/seamless/stainless-steel-round-pipe1.png',
        schedule40SeamlessStainlessSteelPipe1Png: '/Steel/pipes-tubes/types/seamless/schedule-40-seamless-stainless-steel-pipe1.png',
        coldRolledSeamlessStainlessSteelPipe1Png: '/Steel/pipes-tubes/types/seamless/cold-rolled-seamless-stainless-steel-pipe1.png',
        stainlessSteelHighPressurePipe1Png: '/Steel/pipes-tubes/types/seamless/stainless-steel-high-pressure-pipe1.png',
      },
      erw: {
        stainlessSteelWeldedPipe1Png: '/Steel/pipes-tubes/types/erw/stainless-steel-welded-pipe1.png',
        stainlessSteelEfwPipe1Png: '/Steel/pipes-tubes/types/erw/stainless-steel-efw-pipe1.png',
        largeDiameterStainlessSteelWeldedPipe1Png: '/Steel/pipes-tubes/types/erw/large-diameter-stainless-steel-welded-pipe1.png',
        stainlessSteelSpiralWeldedPipe1Png: '/Steel/pipes-tubes/types/erw/stainless-steel-spiral-welded-pipe1.png',
        sch10SsWeldedPipe1Png: '/Steel/pipes-tubes/types/erw/sch-10-ss-welded-pipe1.png',
      },
      tube: {
        stainlessSteelSeamlessTube11Png: '/Steel/placeholder-stainlessSteelSeamlessTube11Png.jpg',
        ssWeldedTubing11Png: '/Steel/placeholder-ssWeldedTubing11Png.jpg',
        coldDrawnStainlessSteelTube11Png: '/Steel/placeholder-coldDrawnStainlessSteelTube11Png.jpg',
        stainlessSteelRoundTube11Png: '/Steel/placeholder-stainlessSteelRoundTube11Png.jpg',
        ssThickWallTubes11Png: '/Steel/placeholder-ssThickWallTubes11Png.jpg',
      },
      polished: {
        stainlessSteelPolishedPipe1Png: '/Steel/pipes-tubes/types/polished/stainless-steel-polished-pipe1.png',
        stainlessSteelPolishedTubing1Png: '/Steel/pipes-tubes/types/polished/stainless-steel-polished-tubing1.png',
        astmA554Gr304PolishedPipe1Png: '/Steel/pipes-tubes/types/polished/astm-a554-gr-304-polished-pipe1.png',
        polishedStainlessSteelTube1Png: '/Steel/pipes-tubes/types/polished/polished-stainless-steel-tube1.png',
        astmA554Gr201PolishedPipe1Png: '/Steel/pipes-tubes/types/polished/astm-a554-gr-201-polished-pipe1.png',
      },
      heatExchanger: {
        stainlessSteelHeatExchangerTubes1Png: '/Steel/pipes-tubes/types/heat-exchanger/stainless-steel-heat-exchanger-tubes1.png',
        stainlessSteelCoilTubingHeatExchanger1Png: '/Steel/pipes-tubes/types/heat-exchanger/stainless-steel-coil-tubing-heat-exchanger1.png',
        stainlessSteelShellAndTubeHeatExchanger1Png: '/Steel/pipes-tubes/types/heat-exchanger/stainless-steel-shell-and-tube-heat-exchanger1.png',
        stainlessSteelHeatExchangerStraightTubing1Png: '/Steel/pipes-tubes/types/heat-exchanger/stainless-steel-heat-exchanger-straight-tubing1.png',
        ssSeamlessHeatExchangerTubes1Png: '/Steel/pipes-tubes/types/heat-exchanger/ss-seamless-heat-exchanger-tubes1.png',
      },
      boiler: {
        stainlessSteelBoilerTube1Png: '/Steel/pipes-tubes/types/boiler/stainless-steel-boiler-tube1.png',
        ss304SeamlessBoilerTubing1Png: '/Steel/pipes-tubes/types/boiler/ss-304-seamless-boiler-tubing1.png',
        stainlessSteelWaterTubeBoiler1Png: '/Steel/pipes-tubes/types/boiler/stainless-steel-water-tube-boiler1.png',
        ssSeamlessBoilerTubes1Png: '/Steel/pipes-tubes/types/boiler/ss-seamless-boiler-tubes1.png',
        stainlessSteelWeldedBoilerTube1Png: '/Steel/pipes-tubes/types/boiler/stainless-steel-welded-boiler-tube1.png',
      },
      duplex: {
        duplex2205SeamlessPipe1Png: '/Steel/pipes-tubes/types/duplex/duplex-2205-seamless-pipe1.png',
        duplex2205Tube1Png: '/Steel/pipes-tubes/types/duplex/duplex-2205-tube1.png',
        astmA790GrS32205Tubing1Png: '/Steel/pipes-tubes/types/duplex/astm-a790-gr-s32205-tubing1.png',
        duplexStainlessSteelPipe1Png: '/Steel/pipes-tubes/types/duplex/duplex-stainless-steel-pipe1.png',
        '2205SteelErwPipe1Pngg': '/Steel/placeholder-2205SteelErwPipe1Pngg.jpg',
      },
      hollow: {
        stainlessSteelSquareHollowSection1Png: '/Steel/pipes-tubes/types/hollow/stainless-steel-square-hollow-section1.png',
        stainlessSteelCircularHollowSection1Png: '/Steel/pipes-tubes/types/hollow/stainless-steel-circular-hollow-section1.png',
        astmA554Grade201RectangularHollowTube1Png: '/Steel/pipes-tubes/types/hollow/astm-a554-grade-201-rectangular-hollow-tube1.png',
        ss316CircularHollowTube1Png: '/Steel/pipes-tubes/types/hollow/ss-316-circular-hollow-tube1.png',
        astmA554Tp316lSeamlessHollowTube1Png: '/Steel/pipes-tubes/types/hollow/astm-a554-tp-316l-seamless-hollow-tube1.png',
      },
      conduit: {
        stainlessSteelConduitTube1Png: '/Steel/pipes-tubes/types/conduit/stainless-steel-conduit-tube1.png',
        stainlessSteelConduits1Png: '/Steel/pipes-tubes/types/conduit/stainless-steel-conduits1.png',
        electricalMetallicTubing1Png: '/Steel/pipes-tubes/types/conduit/electrical-metallic-tubing1.png',
        aisi316lRigidStainlessSteelConduit1Png: '/Steel/pipes-tubes/types/conduit/aisi-316l-rigid-stainless-steel-conduit1.png',
        stainlessSteelFlexibleConduit1Png: '/Steel/pipes-tubes/types/conduit/stainless-steel-flexible-conduit1.png',
      },
    },
    erwPipe1: '/Steel/pipes-tubes/erw-pipe1.png',
    industrialTube1: '/Steel/pipes-tubes/industrial-tube1.png',
    polishedTube1: '/Steel/pipes-tubes/polished-tube1.png',
    heatExchangerTube1: '/Steel/pipes-tubes/heat-exchanger-tube1.png',
    boilerTube1: '/Steel/pipes-tubes/boiler-tube1.png',
    conduitPipe: '/Steel/pipes-tubes/conduit-pipe.jpg',
    seamlessPipe: '/Steel/pipes-tubes/seamless-pipe.jpg',
    duplexPipe1: '/Steel/pipes-tubes/duplex-pipe1.png',
    hollowSection1: '/Steel/pipes-tubes/hollow-section1.png',
    conduitPipe1: '/Steel/pipes-tubes/conduit-pipe1.png',
  },
  sheetsPlates: {
    sheetsPlates: '/Steel/SHEETS&PLATES.png',
    ssSheets: '/Steel/sheets-plates/shared/ss-sheets.png',
    ssPlates: '/Steel/sheets-plates/shared/ss-plates.png',
    steelCoils: '/Steel/sheets-plates/shared/steel-coils.png',
    ssStrips: '/Steel/sheets-plates/shared/ss-strips.png',
    ssCircle: '/Steel/sheets-plates/shared/ss-circle.png',
    types: {
      ssPerforatedSheet: '/Steel/sheets-plates/shared/ss-perforated-sheet.png',
      csPerforatedSheet: '/Steel/sheets-plates/shared/cs-perforated-sheet.png',
    },
    ssChequeredPlate: '/Steel/sheets-plates/shared/ss-chequered-plate.png',
    ssFlats: '/Steel/sheets-plates/shared/ss-flats.png',
    csCoils: '/Steel/sheets-plates/shared/cs-coils.jpg',
    csSheets: '/Steel/sheets-plates/shared/cs-sheets.png',
    csPlates: '/Steel/sheets-plates/shared/cs-plates.png',
    carbonCoils: '/Steel/sheets-plates/shared/carbon-coils.png',
    csStips: '/Steel/sheets-plates/shared/cs-stips.png',
    csFoils: '/Steel/sheets-plates/shared/cs-foils.png',
    csChequeredPlate: '/Steel/sheets-plates/shared/cs-chequered-plate.png',
    csCircles: '/Steel/sheets-plates/shared/cs-circles.png',
    ssCoils: '/Steel/sheets-plates/shared/ss-coils.jpg',
    ssFoils: '/Steel/sheets-plates/shared/ss-foils.png',
    ssPerforatedSheet: '/Steel/sheets-plates/shared/ss-perforated-sheet.png',
  },
  pipeFittings: {
    types: {
      buttWeld: {
        pipeFittingElbowCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-elbow-card.jpg',
        pipeFittingTeeCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-tee-card.jpg',
        pipeFittingReducersCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-reducers-card.jpg',
        pipeFittingPipeBendCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-pipe-bend-card.jpg',
        pipeFittingStubEndCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-stub-end-card.jpg',
        pipeFittingCapCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-cap-card.jpg',
        pipeFittingCrossCard: '/Steel/pipe-fittings/types/butt-weld/pipe-fitting-cross-card.jpg',
      },
      forged: {
        forgedFittingElbowCard: '/Steel/pipe-fittings/types/forged/forged-fitting-elbow-card.jpg',
        forgedFittingCrossTee: '/Steel/pipe-fittings/types/forged/forged-fitting-cross-tee.jpg',
        forgedFittingsCap: '/Steel/pipe-fittings/types/forged/forged-fittings-cap.jpg',
        forgedFittingsUnion: '/Steel/pipe-fittings/types/forged/forged-fittings-union.jpg',
        forgedFittingsPlugBushing: '/Steel/pipe-fittings/types/forged/forged-fittings-plug-bushing.jpg',
        forgedFittingsSwageNipple: '/Steel/pipe-fittings/types/forged/forged-fittings-swage-nipple.jpg',
      },
    },
  },
  flanges: {
    slipOnFlange: '/Steel/flanges/slip-on-flange.jpg',
    blindSpectacleBlindBanner: '/Steel/flanges/blind-spectacle-blind-banner.jpg',
    lapJointFlangeBanner: '/Steel/flanges/lap-joint-flange-banner.jpg',
    socketWeldFlangeBanner: '/Steel/flanges/socket-weld-flange-banner.jpg',
    weldNeckFlange: '/Steel/flanges/weld-neck-flange.jpg',
    orificeFlangeBanner: '/Steel/flanges/orifice-flange-banner.jpg',
    threadedFlangeBanner: '/Steel/flanges/threaded-flange-banner.jpg',
  },
  fasteners: {
    stainless: '/Steel/fasteners-bars/stainless.jpg',
    types: {
      stainlessFasteners: {
        s1: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s1.png',
        s2: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s2.png',
        s3: '/Steel/fasteners-bars/types/special-fasteners-bars/s3.png',
        s4: '/Steel/fasteners-bars/types/special-fasteners-bars/s4.png',
        s6: '/Steel/fasteners-bars/types/special-fasteners-bars/s6.png',
        s7: '/Steel/fasteners-bars/types/special-fasteners-bars/s7.png',
        s8: '/Steel/fasteners-bars/types/special-fasteners-bars/s8.png',
        s9: '/Steel/fasteners-bars/types/special-fasteners-bars/s9.png',
        s10: '/Steel/fasteners-bars/types/special-fasteners-bars/s10.png',
        s11: '/Steel/fasteners-bars/types/special-fasteners-bars/s11.png',
        s12: '/Steel/fasteners-bars/types/special-fasteners-bars/s12.png',
        s13: '/Steel/fasteners-bars/types/special-fasteners-bars/s13.png',
      },
      hexBolts: {
        hex1: '/Steel/fasteners-bars/types/hex-bolts/hex1.png',
        hex2: '/Steel/fasteners-bars/types/hex-bolts/hex2.png',
        hex3: '/Steel/fasteners-bars/types/hex-bolts/hex3.png',
        hex4: '/Steel/fasteners-bars/types/hex-bolts/hex4.png',
      },
      hexNuts: {
        n1: '/Steel/fasteners-bars/types/hex-nuts/n1.png',
        n2: '/Steel/fasteners-bars/types/hex-nuts/n2.png',
        n4: '/Steel/fasteners-bars/types/hex-nuts/n4.png',
        in1: '/Steel/fasteners-bars/types/hex-nuts/in1.png',
        in3: '/Steel/fasteners-bars/types/hex-nuts/in3.png',
        in4: '/Steel/fasteners-bars/types/hex-nuts/in4.png',
        in5: '/Steel/fasteners-bars/types/hex-nuts/in5.png',
      },
      washers: {
        w1: '/Steel/fasteners-bars/types/washers/w1.png',
        w2: '/Steel/fasteners-bars/types/washers/w2.png',
        w3: '/Steel/fasteners-bars/types/washers/w3.png',
        w4: '/Steel/fasteners-bars/types/washers/w4.png',
      },
      petrochemicalStudBolts: {
        s1: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s1.png',
        s2: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s2.png',
      },
      structuralAssemblies: {
        a1: '/Steel/fasteners-bars/types/structural-assemblies/a1.png',
        a2: '/Steel/fasteners-bars/types/structural-assemblies/a2.png',
        a3: '/Steel/fasteners-bars/types/structural-assemblies/a3.png',
        a4: '/Steel/fasteners-bars/types/structural-assemblies/a4.png',
        a5: '/Steel/fasteners-bars/types/structural-assemblies/a5.png',
        a6: '/Steel/fasteners-bars/types/structural-assemblies/a6.png',
        a7: '/Steel/fasteners-bars/types/structural-assemblies/a7.png',
        a9: '/Steel/fasteners-bars/types/structural-assemblies/a9.png',
        a10: '/Steel/fasteners-bars/types/structural-assemblies/a10.png',
        a11: '/Steel/fasteners-bars/types/structural-assemblies/a11.png',
        a12: '/Steel/fasteners-bars/types/structural-assemblies/a12.png',
        a13: '/Steel/fasteners-bars/types/structural-assemblies/a13.png',
        a15: '/Steel/fasteners-bars/types/structural-assemblies/a15.png',
        a16: '/Steel/fasteners-bars/types/structural-assemblies/a16.png',
        a17: '/Steel/fasteners-bars/types/structural-assemblies/a17.png',
        a18: '/Steel/fasteners-bars/types/structural-assemblies/a18.png',
        a19: '/Steel/fasteners-bars/types/structural-assemblies/a19.png',
        a20: '/Steel/fasteners-bars/types/structural-assemblies/a20.png',
        a21: '/Steel/fasteners-bars/types/structural-assemblies/a21.png',
        a22: '/Steel/fasteners-bars/types/structural-assemblies/a22.png',
        a23: '/Steel/fasteners-bars/types/structural-assemblies/a23.png',
        a24: '/Steel/fasteners-bars/types/structural-assemblies/a24.png',
      },
      specialFastenersBars: {
        s1: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s1.png',
        s2: '/Steel/fasteners-bars/types/petrochemical-stud-bolts/s2.png',
        s3: '/Steel/fasteners-bars/types/special-fasteners-bars/s3.png',
        s4: '/Steel/fasteners-bars/types/special-fasteners-bars/s4.png',
        s5: '/Steel/fasteners-bars/types/special-fasteners-bars/s5.png',
        s6: '/Steel/fasteners-bars/types/special-fasteners-bars/s6.png',
        s7: '/Steel/fasteners-bars/types/special-fasteners-bars/s7.png',
        s8: '/Steel/fasteners-bars/types/special-fasteners-bars/s8.png',
        s9: '/Steel/fasteners-bars/types/special-fasteners-bars/s9.png',
        s10: '/Steel/fasteners-bars/types/special-fasteners-bars/s10.png',
        s11: '/Steel/fasteners-bars/types/special-fasteners-bars/s11.png',
        s12: '/Steel/fasteners-bars/types/special-fasteners-bars/s12.png',
        s13: '/Steel/fasteners-bars/types/special-fasteners-bars/s13.png',
        s14: '/Steel/fasteners-bars/types/special-fasteners-bars/s14.png',
        s15: '/Steel/fasteners-bars/types/special-fasteners-bars/s15.png',
        s16: '/Steel/fasteners-bars/types/special-fasteners-bars/s16.png',
        s17: '/Steel/fasteners-bars/types/special-fasteners-bars/s17.png',
        s18: '/Steel/fasteners-bars/types/special-fasteners-bars/s18.png',
        s19: '/Steel/fasteners-bars/types/special-fasteners-bars/s19.png',
      },
    },
    hexbolts: '/Steel/fasteners-bars/hexbolts.jpg',
    hexnut: '/Steel/fasteners-bars/hexnut.jpg',
    washers: '/Steel/fasteners-bars/washers.jpg',
    studbolt: '/Steel/fasteners-bars/studbolt.jpg',
    structurebolt: '/Steel/fasteners-bars/structurebolt.jpg',
    special: '/Steel/fasteners-bars/special.jpg',
  },
  sealingGaskets: {
    types: {
      ringGasket: {
        ringGasketOctagonal: '/Steel/sealing-gaskets/types/ring-gasket/ring-gasket---octagonal.jpg',
        ringGasketOval: '/Steel/sealing-gaskets/types/ring-gasket/ring-gasket---oval.jpg',
        bxTypeRingGaskets: '/Steel/sealing-gaskets/types/ring-gasket/bx-type-ring-gaskets.png',
        sbxTypeRingGaskets: '/Steel/sealing-gaskets/types/ring-gasket/sbx-type-ring-gaskets.jpg',
        rxTypesRingGaskets: '/Steel/sealing-gaskets/types/ring-gasket/rx-types-ring-gaskets.png',
        zincCoatedRingGasket: '/Steel/sealing-gaskets/types/ring-gasket/zinc-coated-ring-gasket.jpg',
        seatRings: '/Steel/sealing-gaskets/types/ring-gasket/seat-rings.jpg',
        silverCoatedGasket: '/Steel/sealing-gaskets/types/ring-gasket/silver-coated-gasket.jpg',
        lipSeal: '/Steel/sealing-gaskets/types/ring-gasket/lip-seal.jpg',
        bonnetGasket: '/Steel/sealing-gaskets/types/ring-gasket/bonnet-gasket.jpg',
        ringGasketWithPtfeInserted: '/Steel/sealing-gaskets/types/ring-gasket/ring-gasket-with-ptfe-inserted.png',
        bridgemanGaskets: '/Steel/sealing-gaskets/types/ring-gasket/bridgeman-gaskets.png',
        rTypeKammprofileGasketsAdapter: '/Steel/sealing-gaskets/types/ring-gasket/r-type-kammprofile-gaskets---adapter.png',
        ringTypeBlindGaskets: '/Steel/sealing-gaskets/types/ring-gasket/ring-type-blind-gaskets.png',
        rTypeKammprofileGasketsOctagonal: '/Steel/sealing-gaskets/types/ring-gasket/r-type-kammprofile-gaskets---octagonal.png',
      },
      spiralWoundGasket: {
        typeCgi: '/Steel/sealing-gaskets/types/spiral-wound-gasket/type-cgi.jpg',
        typeCg: '/Steel/sealing-gaskets/types/spiral-wound-gasket/type-cg.jpg',
        typeGi: '/Steel/sealing-gaskets/types/spiral-wound-gasket/type-gi.jpg',
        typeG: '/Steel/sealing-gaskets/types/spiral-wound-gasket/type-g.jpg',
      },
      ixGaskets: {
        ixRingAssembledInCompactFlangePosition: '/Steel/sealing-gaskets/types/ix-gaskets/ix-ring-assembled-in-compact-flange-position.jpg',
        ixRingBlue: '/Steel/sealing-gaskets/types/ix-gaskets/ix-ring-blue.jpg',
        ixRingOrange: '/Steel/sealing-gaskets/types/ix-gaskets/ix-ring-orange.jpg',
        ixRingYellow: '/Steel/sealing-gaskets/types/ix-gaskets/ix-ring-yellow.jpg',
      },
      insulationGasket: {
        typeD: '/Steel/sealing-gaskets/types/insulation-gasket/type-d.jpg',
        typeDG10: '/Steel/sealing-gaskets/types/insulation-gasket/type-d-g10.jpg',
        typeE: '/Steel/sealing-gaskets/types/insulation-gasket/type-e.jpg',
        typeF: '/Steel/sealing-gaskets/types/insulation-gasket/type-f.jpg',
        typeFG10316: '/Steel/sealing-gaskets/types/insulation-gasket/type-f-g10-316.jpg',
        typeFG10Ptf: '/Steel/sealing-gaskets/types/insulation-gasket/type-f-g10-ptf.jpg',
      },
      rubberGasket: {
        fullFaceType: '/Steel/sealing-gaskets/types/rubber-gasket/full-face-type.jpg',
        raisedFace: '/Steel/sealing-gaskets/types/rubber-gasket/raised-face.jpg',
        customizedRubberGasket: '/Steel/sealing-gaskets/types/rubber-gasket/customized-rubber-gasket.jpg',
      },
      metalGasket: {
        spiralWoundGasket: '/Steel/sealing-gaskets/spiral-wound-gasket.png',
        metalJacketedGaskets: '/Steel/sealing-gaskets/types/metal-gasket/metal-jacketed-gaskets.jpg',
        ringGaskets: '/Steel/sealing-gaskets/types/metal-gasket/ring-gaskets.jpg',
      },
      hammerUnion: {
        fig50Union: '/Steel/sealing-gaskets/types/hammer-union/fig-50-union.jpg',
        fig100Union: '/Steel/sealing-gaskets/types/hammer-union/fig-100-union.jpg',
        fig200Union: '/Steel/sealing-gaskets/types/hammer-union/fig-200-union.jpg',
        fig206Union: '/Steel/sealing-gaskets/types/hammer-union/fig-206-union.jpg',
        fig211Union: '/Steel/sealing-gaskets/types/hammer-union/fig-211-union.jpg',
        fig400Union: '/Steel/sealing-gaskets/types/hammer-union/fig-400-union.jpg',
        fig600Union: '/Steel/sealing-gaskets/types/hammer-union/fig-600-union.jpg',
        fig602Union: '/Steel/sealing-gaskets/types/hammer-union/fig-602-union.jpg',
        fig1002Union: '/Steel/sealing-gaskets/types/hammer-union/fig-1002-union.jpg',
        fig1003Union: '/Steel/sealing-gaskets/types/hammer-union/fig-1003-union.jpg',
        fig1502Union: '/Steel/sealing-gaskets/types/hammer-union/fig-1502-union.jpg',
        fig20022202Union: '/Steel/sealing-gaskets/types/hammer-union/fig-2002-2202-union.jpg',
      },
      ptfeAndCnafGaskets: {
        reinforcedgraphiteGasketReinforcements: '/Steel/sealing-gaskets/types/ptfe-and-cnaf-gaskets/reinforcedgraphite-gasket-reinforcements.jpg',
        generalCompressedNonAsbestosFibre: '/Steel/sealing-gaskets/types/ptfe-and-cnaf-gaskets/general-compressed-non-asbestos-fibre.jpg',
      },
      metalJacketedGasket: {
        singleJacketedGasket: '/Steel/sealing-gaskets/types/metal-jacketed-gasket/single-jacketed-gasket.jpg',
        corrugatedGasket: '/Steel/sealing-gaskets/types/metal-jacketed-gasket/corrugated-gasket.jpg',
        solidGasket: '/Steel/sealing-gaskets/types/metal-jacketed-gasket/solid-gasket.jpg',
        metalJacktedGasket: '/Steel/sealing-gaskets/types/metal-jacketed-gasket/metal-jackted-gasket.jpg',
      },
    },
  },
};
