"use client";

import React, { useRef, useState, useEffect } from 'react';
import Link from "next/link";
import { motion, useScroll, useTransform, useInView, Variants } from 'framer-motion';
import Image from 'next/image';
import { SITE_IMAGES } from '@/config/images';

/* ─── SECTION NAV ───────────────────────────────────────────── */
const NAV_ITEMS = [
  { label: 'Overview', id: 'overview' },
  { label: 'Why Metallo', id: 'why-metallo' },
  { label: 'Audiences', id: 'audiences' },
  { label: 'Products', id: 'products' },
  { label: 'How It Works', id: 'how-it-works' },
  { label: 'Technical', id: 'technical' },
  { label: 'Benefits', id: 'benefits' },
];

/* ─── PRODUCT DATA (Welding Focus) ───────────────────────────── */
const PRODUCTS = [
  {
    title: 'Submerged Arc (SAW) Solutions',
    icon: 'waves',
    useCases: 'Continuous deep-penetration seams on pressure vessels, wind tower masts, and thick-plate girders.',
    assurance: 'High-basicity fluxes and precision-drawn SAW wires conforming to ASME Section II & EN ISO 14174.',
    image: SITE_IMAGES.welding.heavyEngineering.products.saw,
  },
  {
    title: 'High-Deposition FCAW Consumables',
    icon: 'layers',
    useCases: 'Heavy structural joints, mining crusher fabrication, out-of-position thick steel sections.',
    assurance: 'AWS A5.20/A5.29 certified seamless flux-cored wires with exceptional sub-zero Charpy impact toughness.',
    image: SITE_IMAGES.welding.heavyEngineering.products.fcaw,
  },
  {
    title: 'Advanced Thermal Engineering',
    icon: 'thermostat',
    useCases: 'Pre-heating extremely thick joints and managing Post-Weld Heat Treatment (PWHT) profiles.',
    assurance: 'WB Alloys induction heating engineers deploy automated temperature profiling compliant with ASME VIII.',
    image: SITE_IMAGES.welding.heavyEngineering.products.thermal,
  },
  {
    title: 'Heavy-Duty Fume Extraction',
    icon: 'air',
    useCases: 'Capturing massive fume volumes from continuous SAW and FCAW processes in enclosed vessels.',
    assurance: 'High-capacity Kemper central filtration systems and localized BOHS-compliant capture arms.',
    image: SITE_IMAGES.welding.heavyEngineering.products.fumeExtraction,
  },
  {
    title: 'NDT & Structural Validation',
    icon: 'troubleshoot',
    useCases: 'In-process and final weld inspection for mega-scale fabrications requiring Tier-1 EPC sign-off.',
    assurance: 'Mobilization of UT (including TOFD), Radiography, and MPI engineers directly to fabrication yards.',
    image: SITE_IMAGES.welding.heavyEngineering.products.ndt,
  },
];

/* ─── PROCESS STEPS ─────────────────────────────────────────── */
const PROCESS_STEPS = [
  { title: 'Thick-Plate Assessment', desc: 'Metallo engineers evaluate your base materials, thickness, and applicable codes (ASME VIII, EN 13480).', icon: 'troubleshoot' },
  { title: 'Consumable & Flux Mapping', desc: 'Selection of optimal SAW wire/flux combinations or seamless FCAW wires to maximize safe deposition rates.', icon: 'layers' },
  { title: 'Thermal Profile Setup', desc: 'Deployment of induction heating systems and thermocouples to establish compliant pre-heat and PWHT cycles.', icon: 'thermostat' },
  { title: 'Welding Execution & Extraction', desc: 'Continuous deep-penetration welding accompanied by heavy-duty localized fume extraction to protect operators.', icon: 'precision_manufacturing' },
  { title: 'NDT Validation & Handover', desc: 'Rigorous UT/TOFD and Radiographic inspection resulting in fully traceable, audited project documentation.', icon: 'verified' },
];

/* ─── BENEFITS ──────────────────────────────────────────────── */
const BENEFITS = [
  { title: 'Zero Mega-Scale Rework', desc: 'Precise thermal control and clean filler metals eliminate devastatingly expensive rework on massive components.', icon: 'shield' },
  { title: 'Maximum Deposition', desc: 'Optimized SAW and FCAW setups allow you to lay down pounds of metal per hour, shrinking fabrication timelines.', icon: 'speed' },
  { title: 'Thermal Compliance', desc: 'Guaranteed PWHT profiles ensure your pressure vessels pass severe ASME Section VIII inspections.', icon: 'thermostat' },
  { title: 'Workforce Protection', desc: 'High-capacity LEV systems mitigate the extreme fume clouds generated by continuous heavy-flux welding.', icon: 'health_and_safety' },
  { title: 'End-to-End Control', desc: 'One partner managing your consumables, induction heating, and NDT validation—eliminating supply chain chaos.', icon: 'hub' },
];

/* ─── ANIMATION VARIANTS ────────────────────────────────────── */
const fadeUp: Variants = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, delay: i * 0.1, ease: 'easeOut' },
  }),
};

/* ─── ANIMATED SECTION WRAPPER ──────────────────────────────── */
const AnimatedSection: React.FC<{ children: React.ReactNode; className?: string; id?: string }> = ({ children, className = '', id }) => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-80px' });
  return (
    <div ref={ref} id={id} className={className}>
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        animate={isInView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.6, ease: 'easeOut' }}
      >
        {children}
      </motion.div>
    </div>
  );
};

const MotionImage = motion(Image);

/* ═══════════════════════════════════════════════════════════════
   WELDING - HEAVY ENGINEERING PAGE
   ═══════════════════════════════════════════════════════════════ */
const WeldingHeavyEngineering: React.FC = () => {
  const heroRef = useRef(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] });
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 150]);
  const heroOpacity = useTransform(scrollYProgress, [0, 0.6], [1, 0]);

  const [activeSection, setActiveSection] = useState('overview');

  useEffect(() => {
    const handleScroll = () => {
      const sections = NAV_ITEMS.map(item => ({
        id: item.id,
        el: document.getElementById(item.id),
      }));
      const scrollPos = window.scrollY + 180;
      for (let i = sections.length - 1; i >= 0; i--) {
        const el = sections[i].el;
        if (el && el.offsetTop <= scrollPos) {
          setActiveSection(sections[i].id);
          break;
        }
      }
    };
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) {
      const offset = 130;
      const top = el.getBoundingClientRect().top + window.scrollY - offset;
      window.scrollTo({ top, behavior: 'smooth' });
    }
  };

  return (
    <div className="w-full bg-white global-justify-wrapper">

      {/* ═══ 1. HERO ═══════════════════════════════════════════════ */}
      <section ref={heroRef} className="relative w-full overflow-hidden" style={{ height: "clamp(400px, 60vh, 700px)" }}>
        <MotionImage
          src={SITE_IMAGES.welding.heavyEngineering.hero}
          alt="Heavy engineering submerged arc welding"
          fill
          className="object-cover"
          sizes="100vw"
          priority
          style={{ y: heroY }}
        />

        <motion.div
          className="relative z-10 flex flex-col justify-center h-full container"
          style={{ opacity: heroOpacity }}
        >
          <div className="max-w-3xl inset-0 bg-slate-900/60 p-8 rounded-xl backdrop-blur-sm">
            {/* Breadcrumb */}
            <nav className="flex items-center gap-2 text-sm text-slate-300 mb-8 font-sans">
              <Link href="/" className="hover:text-white transition-colors">Home</Link>
              <span className="material-symbols-outlined text-xs">chevron_right</span>
              <Link href="/welding" className="hover:text-white transition-colors">Welding & Allied</Link>
              <span className="material-symbols-outlined text-xs">chevron_right</span>
              <span className="text-yellow-500 font-medium">Heavy Engineering &amp; Fabrication</span>
            </nav>

            <h1 className="text-4xl md:text-5xl lg:text-6xl font-heading font-extrabold text-white leading-[1.05] mb-6">
              Deep Penetration.<br />
              <span className="text-yellow-500">Absolute Structural Assurance.</span>
            </h1>

            <p className="text-lg md:text-xl text-slate-200 max-w-2xl mb-10 font-sans leading-relaxed">
              Deploying high-deposition consumables, thermal engineering, and NDT expertise for pressure vessels, heavy machinery, and mega-scale fabrications.
            </p>


          </div>
        </motion.div>

        <div className="absolute bottom-0 inset-x-0 h-1 bg-gradient-to-r from-yellow-500 via-yellow-500/60 to-transparent z-10" />
      </section>

      {/* ═══ STICKY SECTION NAV ══════════════════════════════════ */}
      <nav className="sticky top-0 z-40 bg-white border-b border-slate-200 shadow-sm">
        <div className="container">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-0 overflow-x-auto" style={{ scrollbarWidth: 'none' }}>
              {NAV_ITEMS.map((item) => (
                <button
                  key={item.id}
                  onClick={() => scrollToSection(item.id)}
                  className={`relative whitespace-nowrap px-5 py-4 text-sm font-heading font-bold uppercase tracking-wider transition-colors shrink-0 ${activeSection === item.id
                    ? 'text-yellow-600'
                    : 'text-slate-500 hover:text-metallo-navy'
                    }`}
                >
                  {item.label}
                  {activeSection === item.id && (
                    <span className="absolute bottom-0 left-0 right-0 h-[3px] bg-yellow-500 rounded-t" />
                  )}
                </button>
              ))}
            </div>

            <Link
              href="/products/welding"
              className="hidden md:flex items-center gap-1 text-sm font-bold font-heading text-metallo-navy hover:text-yellow-600 transition-colors uppercase tracking-wider whitespace-nowrap px-4"
            >
              <span className="material-symbols-outlined text-base">arrow_back</span>
              Overview
            </Link>
          </div>
        </div>
      </nav>

      {/* ═══ 2. OVERVIEW ═══════════════════════════════════════════ */}
      <AnimatedSection id="overview" className="py-20 lg:py-24 bg-white border-b border-slate-100">
        <div className="container">
          <div className="w-full">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-4">Overview</p>
            <h2 className="text-3xl md:text-4xl font-heading font-extrabold text-metallo-navy leading-tight mb-8">
              Metallo × WB Alloys for Heavy Engineering
            </h2>

            <div className="text-base text-slate-700 font-sans leading-relaxed space-y-5 mb-12">
              <p>
                Fabricating multi-ton pressure vessels, heavy earth-moving machinery, and colossal wind tower masts requires mastering the extreme physics of thick-plate welding. In these mega-scale environments, defects are extraordinarily expensive, and heat input control is a matter of structural survival. Metallo × WB Alloys provides an end-to-end metallurgical ecosystem tailored specifically for heavy engineering. By combining high-deposition Submerged Arc (SAW) fluxes, deployable induction heating engineers for precise PWHT, and rigorous NDT validation, we eliminate the immense cost of fabrication rework. We give heavy fabricators absolute control over their thermal environments and metallurgical outcomes, ensuring every deep-penetration weld meets draconian ASME and ISO tolerances.
              </p>
            </div>
          </div>

          {/* Market Context + Challenges + Solutions grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Market Context */}
            <div className="bg-slate-50 rounded-xl p-7 border border-slate-100">
              <div className="flex items-center gap-3 mb-5">
                <span className="material-symbols-outlined text-2xl text-yellow-600">trending_up</span>
                <h3 className="text-lg font-heading font-bold text-metallo-navy">Market Context</h3>
              </div>
              <ul className="space-y-3">
                {[
                  'Mega-scale fabrications demand incredibly high deposition rates to remain profitable over prolonged construction schedules.',
                  'Thick-plate carbon and alloy steels require strict adherence to pre-heat and Post-Weld Heat Treatment (PWHT) codes to prevent cracking.',
                  'Rigorous Non-Destructive Testing (NDT) like UT/TOFD is mandatory to detect deep sub-surface inclusions.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-slate-600 font-sans leading-relaxed">
                    <span className="material-symbols-outlined text-sm text-yellow-500 mt-0.5 shrink-0">circle</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* Key Challenges */}
            <div className="bg-slate-50 rounded-xl p-7 border border-slate-100">
              <div className="flex items-center gap-3 mb-5">
                <span className="material-symbols-outlined text-2xl text-red-500">warning</span>
                <h3 className="text-lg font-heading font-bold text-metallo-navy">Key Challenges</h3>
              </div>
              <ul className="space-y-3">
                {[
                  'Relying on fragmented suppliers for wire, thermal equipment, and NDT engineers leads to inconsistent heat inputs and failed welds.',
                  'Repairing a deep-penetration defect on a 4-inch thick steel plate costs tens of thousands of dollars in gouging and re-welding.',
                  'Continuous heavy-flux processes generate massive, hazardous fume volumes that overwhelm standard workshop ventilation.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-slate-600 font-sans leading-relaxed">
                    <span className="material-symbols-outlined text-sm text-red-400 mt-0.5 shrink-0">close</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* How Metallo Solves */}
            <div className="bg-metallo-navy rounded-xl p-7">
              <div className="flex items-center gap-3 mb-5">
                <span className="material-symbols-outlined text-2xl text-yellow-500">check_circle</span>
                <h3 className="text-lg font-heading font-bold text-white">How Metallo Solves This</h3>
              </div>
              <ul className="space-y-3">
                {[
                  { label: 'Thermal Mastery', desc: 'Deploying WB Alloys induction heating engineers to manage precise PWHT, removing the burden from the fabricator.' },
                  { label: 'High-Yield Consumables', desc: 'Direct-manufactured SAW fluxes and FCAW wires that maximize deposition while maintaining Charpy toughness.' },
                  { label: 'Integrated NDT', desc: 'Mobilizing UT and Radiography teams to validate structural integrity without coordinating third-party inspectors.' },
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-slate-300 font-sans leading-relaxed">
                    <span className="material-symbols-outlined text-sm text-yellow-500 mt-0.5 shrink-0">check</span>
                    <span><strong className="text-white font-semibold">{item.label}:</strong> {item.desc}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 3. VALUE PROPOSITION ══════════════════════════════════ */}
      <AnimatedSection id="why-metallo" className="py-20 lg:py-28 bg-slate-50 border-b border-slate-200">
        <div className="container">
          <div className="text-center mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-3">Why Metallo Welding</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-metallo-navy leading-tight">
              End-to-end metallurgical control<br className="hidden sm:block" /> for mega-projects
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { icon: 'waves', title: 'High-Deposition Fluxes', desc: 'Active and highly-basic SAW fluxes optimized for multiple-pass welding on extraordinarily thick sections.' },
              { icon: 'thermostat', title: 'Thermal Mastery', desc: 'Induction heating engineers ensuring strict adherence to ASME Section VIII PWHT and pre-heating requirements.' },
              { icon: 'troubleshoot', title: 'NDT Validation', desc: 'In-house ultrasonic (UT/TOFD) and radiographic (RT) inspection teams providing immediate flaw detection.' },
              { icon: 'air', title: 'Heavy-Duty Extraction', desc: 'High-capacity Kemper filtration networks engineered specifically to handle immense continuous flux fume volumes.' },
            ].map((item, i) => (
              <motion.div
                key={item.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-60px' }}
                variants={fadeUp}
                className="bg-white rounded-xl p-7 shadow-sm border border-slate-100 hover:shadow-lg hover:border-yellow-200 transition-all duration-300 group"
              >
                <div className="w-12 h-12 rounded-lg bg-metallo-navy/5 flex items-center justify-center mb-5 group-hover:bg-yellow-500/10 transition-colors">
                  <span className="material-symbols-outlined text-2xl text-metallo-navy group-hover:text-yellow-600 transition-colors">{item.icon}</span>
                </div>
                <h3 className="text-lg font-heading font-bold text-metallo-navy mb-2">{item.title}</h3>
                <p className="text-sm text-slate-600 font-sans leading-relaxed">{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 3b. AUDIENCE SEGMENTS ══════════════════════════════════ */}
      <AnimatedSection id="audiences" className="py-20 lg:py-28 bg-white border-b border-slate-100">
        <div className="container">
          <div className="mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-3">Who We Serve</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-metallo-navy leading-tight">
              Welding solutions built for the heavyweights
            </h2>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {[
              {
                icon: 'precision_manufacturing',
                title: 'Pressure Vessel Manufacturers',
                focus: 'ASME VIII Boilers, Heat Exchangers, Storage Tanks',
                copy: 'Constructing pressure vessels requires absolute control over heat inputs. We supply Submerged Arc (SAW) wires and basic fluxes, manage your mandatory Post-Weld Heat Treatment (PWHT) profiles, and validate deep root passes via ultrasonic inspection—ensuring zero failures under extreme pressure tests.',
                assurances: 'SAW Wires & Fluxes · Induction PWHT · UT/TOFD Inspection',
                cta: 'Secure Vessel Integrity',
              },
              {
                icon: 'agriculture',
                title: 'Heavy Machinery & Mining',
                focus: 'Excavator Buckets, Crushers, Earth-Moving Equipment',
                copy: 'Mining equipment suffers horrific abrasion and impact. We deliver premium, high-deposition flux-cored wires (FCAW) and specialized hardfacing consumables that lay down rapidly, providing immense Charpy toughness and superior crack resistance for thick-plate joints.',
                assurances: 'High-Deposition FCAW · Hardfacing Alloys · Rapid Laydown',
                cta: 'Equip Heavy Manufacturing',
              },
              {
                icon: 'sailing',
                title: 'Shipbuilding & Marine',
                focus: 'Hull Blocks, Mega-Structures, Deepwater Modules',
                copy: 'Shipyards require continuous, miles-long welds that must pass maritime classification society rules. We deploy mechanized welding tractors, heavy-duty centralized fume extraction, and robust AWS-certified wires to streamline mega-block assembly and keep shipyard environments clean.',
                assurances: 'Mechanized Tractors · AWS/Marine Grade Wire · Heavy LEV',
                cta: 'Optimize Shipyard Fabrication',
              },
            ].map((a, i) => (
              <motion.div
                key={a.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-60px' }}
                variants={fadeUp}
                className="rounded-xl border border-slate-200 overflow-hidden hover:shadow-lg transition-all duration-300"
              >
                <div className="bg-metallo-navy p-6">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="material-symbols-outlined text-yellow-500 text-3xl">{a.icon}</span>
                    <h3 className="text-xl font-heading font-bold text-white">{a.title}</h3>
                  </div>
                  <p className="text-xs text-slate-400 uppercase tracking-wider font-sans">{a.focus}</p>
                </div>
                <div className="p-6 space-y-4">
                  <p className="text-sm text-slate-600 font-sans leading-relaxed">{a.copy}</p>
                  <div className="border-t border-slate-100 pt-4">
                    <p className="text-[10px] font-heading font-bold text-yellow-600 uppercase tracking-widest mb-1">Assurances</p>
                    <p className="text-xs text-slate-500 font-sans">{a.assurances}</p>
                  </div>
                  <Link href="/contact" className="inline-flex items-center gap-2 text-sm font-heading font-bold text-yellow-600 hover:text-metallo-navy transition-colors">
                    {a.cta}
                    <span className="material-symbols-outlined text-base">arrow_forward</span>
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 4. PRODUCT BLOCKS ══════════════════════════════════════ */}
      <AnimatedSection id="products" className="py-20 lg:py-28 bg-white">
        <div className="container">
          <div className="mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-3">Welding Ecosystem</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-metallo-navy leading-tight">
              Heavy fabrication & thermal tools
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {PRODUCTS.map((product, i) => (
              <motion.div
                key={product.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-40px' }}
                variants={fadeUp}
                className="group relative rounded-xl overflow-hidden bg-metallo-navy shadow-lg h-[360px] cursor-pointer"
              >
                <Image
                  src={product.image}
                  alt={product.title}
                  fill
                  className="object-cover opacity-40 group-hover:opacity-50 transition-all duration-700 group-hover:scale-105"
                  sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-metallo-navy via-metallo-navy/60 to-transparent" />

                <div className="relative z-10 flex flex-col justify-end h-full p-7">
                  <div className="mb-auto pt-1">
                    <span className="material-symbols-outlined text-3xl text-yellow-500">{product.icon}</span>
                  </div>

                  <h3 className="text-xl font-heading font-bold text-white mb-2">{product.title}</h3>

                  <div className="space-y-2">
                    <div>
                      <p className="text-[10px] font-heading font-bold uppercase tracking-widest text-yellow-500 mb-1">Use Cases</p>
                      <p className="text-sm text-slate-300 font-sans leading-snug">{product.useCases}</p>
                    </div>
                    <div>
                      <p className="text-[10px] font-heading font-bold uppercase tracking-widest text-yellow-500 mb-1">Assurance</p>
                      <p className="text-sm text-slate-300 font-sans leading-snug">{product.assurance}</p>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}

            {/* CTA Tile */}
            <motion.div
              custom={5}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: '-40px' }}
              variants={fadeUp}
              className="group rounded-xl overflow-hidden bg-gradient-to-br from-yellow-500 to-yellow-600 shadow-lg h-[360px] flex flex-col items-center justify-center text-center p-8 cursor-pointer hover:from-yellow-400 hover:to-yellow-500 transition-all duration-300"
            >
              <span className="material-symbols-outlined text-5xl text-metallo-navy mb-4">account_tree</span>
              <h3 className="text-2xl font-heading font-extrabold text-metallo-navy mb-3">Executing a<br />Thick-Plate Project?</h3>
              <p className="text-sm text-metallo-navy/70 font-sans mb-6 max-w-md">Need specific SAW basicity flux matching, induction heating deployment, or UT engineers for a mega-scale vessel? We provide full end-to-end management.</p>
              <button className="inline-flex items-center gap-2 px-6 py-3 bg-metallo-navy text-white text-xs font-heading font-bold uppercase tracking-wider hover:bg-metallo-navy/90 transition-colors rounded-sm">
                Engage WB Alloys Engineering
                <span className="material-symbols-outlined text-sm">arrow_forward</span>
              </button>
            </motion.div>
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 5. PROCESS TIMELINE ═════════════════════════════════════ */}
      <AnimatedSection id="how-it-works" className="py-20 lg:py-28 bg-metallo-navy">
        <div className="container">
          <div className="text-center mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-500 mb-3">How It Works</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-white leading-tight">
              From thermal profiling to UT sign-off
            </h2>
            <p className="text-slate-400 font-sans mt-4 max-w-2xl mx-auto">
              A 5-step integration process designed for massive fabrication yards requiring precise heat input control, huge deposition rates, and uncompromising defect inspection.
            </p>
          </div>

          {/* Desktop horizontal stepper */}
          <div className="hidden md:grid md:grid-cols-5 gap-0 relative">
            <div className="absolute top-8 left-[10%] right-[10%] h-0.5 bg-slate-700" />

            {PROCESS_STEPS.map((step, i) => (
              <motion.div
                key={step.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                className="flex flex-col items-center text-center relative"
              >
                <div className="w-16 h-16 rounded-full bg-slate-800 border-2 border-yellow-500/30 flex items-center justify-center mb-5 relative z-10">
                  <span className="material-symbols-outlined text-2xl text-yellow-500">{step.icon}</span>
                </div>
                <span className="text-[10px] font-heading font-bold uppercase tracking-widest text-yellow-500 mb-2">Phase {i + 1}</span>
                <h4 className="text-sm font-heading font-bold text-white mb-2">{step.title}</h4>
                <p className="text-xs text-slate-400 font-sans leading-relaxed max-w-[180px]">{step.desc}</p>
              </motion.div>
            ))}
          </div>

          {/* Mobile vertical stepper */}
          <div className="md:hidden space-y-8">
            {PROCESS_STEPS.map((step, i) => (
              <motion.div
                key={step.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                className="flex gap-5"
              >
                <div className="flex flex-col items-center">
                  <div className="w-12 h-12 rounded-full bg-slate-800 border-2 border-yellow-500/30 flex items-center justify-center shrink-0">
                    <span className="material-symbols-outlined text-xl text-yellow-500">{step.icon}</span>
                  </div>
                  {i < PROCESS_STEPS.length - 1 && <div className="w-0.5 flex-1 bg-slate-700 mt-2" />}
                </div>
                <div className="pb-4">
                  <span className="text-[10px] font-heading font-bold uppercase tracking-widest text-yellow-500">Phase {i + 1}</span>
                  <h4 className="text-base font-heading font-bold text-white mb-1">{step.title}</h4>
                  <p className="text-sm text-slate-400 font-sans leading-relaxed">{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 6. TECHNICAL HIGHLIGHTS ═════════════════════════════════ */}
      <AnimatedSection id="technical" className="py-20 lg:py-28 bg-slate-50 border-b border-slate-200">
        <div className="container">
          <div className="text-center mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-3">Technical &amp; Compliance</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-metallo-navy leading-tight">
              Heavy-duty fabrication standards
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                icon: 'menu_book',
                title: 'Standards & Certifications',
                items: ['ASME Section VIII — Pressure Vessels', 'AWS D1.1 — Structural Welding Code', 'EN 13480 — Metallic Industrial Piping', 'PED 2014/68/EU — Pressure Equipment', 'ISO 9001 / ISO 45001 Compliance', 'BOHS P601 — LEV Compliance Standard'],
              },
              {
                icon: 'science',
                title: 'Testing & Validation',
                items: ['Ultrasonic Testing (UT) / TOFD for thick sections', 'Radiographic Testing (RT) per ASME V', 'Magnetic Particle Inspection (MPI)', 'Charpy impact testing at sub-zero temps', 'PWHT temperature profile recording', 'SAW flux basicity and moisture testing'],
              },
              {
                icon: 'qr_code_2',
                title: 'Traceability',
                items: ['Material Testing Certificates (MTCs) per heat', 'Weld Procedure Specifications (WPS/PQR)', 'PWHT charts and heat treatment records', 'NDT reports with UT/RT scan archives', 'Machine calibration logs (ISO 17662)', 'COSHH and Safety Data Sheets (SDS)'],
              },
            ].map((block, i) => (
              <motion.div
                key={block.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-60px' }}
                variants={fadeUp}
                className="bg-white rounded-xl p-8 shadow-sm border border-slate-100"
              >
                <div className="flex items-center gap-3 mb-6">
                  <span className="material-symbols-outlined text-2xl text-yellow-600">{block.icon}</span>
                  <h3 className="text-lg font-heading font-bold text-metallo-navy">{block.title}</h3>
                </div>
                <ul className="space-y-3">
                  {block.items.map((item) => (
                    <li key={item} className="flex items-start gap-2 text-sm text-slate-600 font-sans">
                      <span className="material-symbols-outlined text-sm text-yellow-500 mt-0.5 shrink-0">check_circle</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 7. BENEFITS & ROI ═══════════════════════════════════════ */}
      <AnimatedSection id="benefits" className="py-20 lg:py-28 bg-white">
        <div className="container">
          <div className="text-center mb-16">
            <p className="text-xs font-heading font-bold uppercase tracking-[0.25em] text-yellow-600 mb-3">Benefits &amp; ROI</p>
            <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-metallo-navy leading-tight">
              Measurable impact on massive projects
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6 mb-16">
            {BENEFITS.map((benefit, i) => (
              <motion.div
                key={benefit.title}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-60px' }}
                variants={fadeUp}
                className="text-center"
              >
                <div className="w-14 h-14 rounded-full bg-yellow-500/10 flex items-center justify-center mx-auto mb-4">
                  <span className="material-symbols-outlined text-2xl text-yellow-600">{benefit.icon}</span>
                </div>
                <h3 className="text-base font-heading font-bold text-metallo-navy mb-2">{benefit.title}</h3>
                <p className="text-sm text-slate-600 font-sans leading-relaxed">{benefit.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </AnimatedSection>

      {/* ═══ 8. FINAL CTA ═══════════════════════════════════════════ */}
      <section className="relative py-20 lg:py-28 overflow-hidden">
        <div className="absolute inset-0">
          <Image
            src={SITE_IMAGES.welding.heavyEngineering.cta}
            alt="Heavy structural steel welding"
            fill
            className="object-cover"
            sizes="100vw"
          />
        </div>
        <div className="absolute inset-0 bg-metallo-navy/90" />

        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-5xl font-heading font-extrabold text-white leading-tight mb-6">
            Ready to secure your<br />heavy fabrication integrity?
          </h2>
          <p className="text-lg text-slate-300 font-sans max-w-2xl mx-auto mb-10">
            From high-deposition SAW fluxes and FCAW wires to induction heating and complete NDT validation — Metallo delivers absolute end-to-end metallurgical control.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="inline-flex items-center gap-3 px-8 py-4 bg-yellow-500 text-metallo-navy text-sm font-heading font-bold uppercase tracking-wider hover:bg-yellow-400 transition-all duration-300">
              <span className="material-symbols-outlined text-xl">layers</span>
              Source Consumables
            </button>
            <button className="inline-flex items-center gap-3 px-8 py-4 border-2 border-white/40 text-white text-sm font-heading font-bold uppercase tracking-wider hover:border-white hover:bg-white/10 transition-all duration-300">
              <span className="material-symbols-outlined text-xl">thermostat</span>
              Thermal Engineering
            </button>
          </div>
        </div>
      </section>

    </div>
  );
};

export default WeldingHeavyEngineering;